name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Github Packages
      run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_BUILDER }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_BUILDER_TOKEN }}
    - name: Build the Docker image
      run: |
        CONTAINER_REF=branch-$(echo "${GITHUB_REF}" | awk '{n=split($0,a,"/"); print a[n]}' | sed 's/branch-master/latest')
        docker build . --file Dockerfile --tag docker.pkg.github.com/${GITHUB_REPOSITORY}/syndromeos:${CONTAINER_REF}
    - name: Publish
      run: |
        CONTAINER_REF=branch-$(echo "${GITHUB_REF}" | awk '{n=split($0,a,"/"); print a[n]}' | sed 's/branch-master/latest')
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/syndromeos:${CONTAINER_REF}
