name: Triage
on:
  issues:
    types: [opened]
jobs:
  applyTriageLabel:
    name: Apply Triage Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Apply Triage Label
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_BUILDER_TOKEN }}
        with:
          args: label triage
  commentOnNewIssues:
    name: Comment On New Issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Comment On New Issues
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_BUILDER_TOKEN }}
        with:
          args: comment "@agilebot here!  Your issue has been received and will be triaged."
